# Site Metadata
title: BlueStar03 Theme
description: â€œFor Documentsâ€
lang: en

title: BlueStar03 Theme

#remote_theme: BlueStar03/theme@v1.0.0

logo: /assets/images/logo.svg

toc_icon: fa fa-list

toc-include-h1: true

font_base: 16px
panel_width: 20em
accent_color: blue
content_max: 70em

fontawesome_kit: fe2b0ce82c

nav:
  - title: ğŸ  Home
    url: /
  - title: ğŸ“ Blog
    url: /blog
  - title: ğŸ“„ Readme
    url: /README



social:
  - title: GitHub
    url: https://github.com/your-user/your-repo
    icon: fab fa-github
  - title: Twitter
    url: https://twitter.com/your-handle
    icon: fab fa-twitter



defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"