title: BlueStar Theme Demo Site
description: A demo site showcasing the BlueStar Jekyll theme.



font_base: 16px
panel_width: 22em
accent_color: blue
content_max: 68em  

toc-include-h1: true
toc_icon: "ğŸ“‘"           # Default Unicode character
# toc_icon: "fas fa-list"  # Or use a Font Awesome icon class

collections:
  gdd:
    output: true


nav:
  - title: .ğŸ  Home
    url: /
    type: page

  - title: ğŸ“œ GDD
    url: /gdd
    type: collection
    collection: gdd

  - title: ğŸ“– Doc
    url: /docs
    type: collection
    collection: docs

  - title: ğŸ“ Devlog
    url: /posts
    type: blog

  - title: ğŸ› ï¸ About
    url: /about
    type: page

  - title: ğŸ—ºï¸ Roadmap
    url: /roadmap
    type: page





markdown: kramdown
kramdown:
  auto_ids: true
  toc_levels: 2..3   # H2 and H3

defaults:
  - scope:
      path: ""          # Empty path means "all files"
    values:
      layout: "default"


# Optional: add plugins if needed
#plugins:
#  - jekyll-feed
#  - jekyll-seo-tag






# Social links appear in the left sidebar footer.
# Each item needs:
# - title: for the tooltip
# - url: the full link
# - icon: Font Awesome class (e.g. 'fab fa-twitter')

social:
  - title: DeviantArt
    url: https://deviantart.com/zbule
    icon: fab fa-deviantart
  # - title: Instagram
  #   url: https://instagram.com/zbule
  #   icon: fab fa-instagram
  # - title: BlueSky
  #   url: https://bsky.app/profile/zbule.xyz
  #   icon: fa-brands fa-bluesky
  # - title: Twitter
  #   url: https://twitter.com/zBuLe
  #   icon: fab fa-twitter
  # - title: itch.io
  #   url: https://zbule.itch.io
  #   icon: fa-brands fa-itch-io
  # - title: Twitch
  #   url: https://twitch.tv/zbule
  #   icon: fab fa-twitch
  # - title: YouTube
  #   url: https://youtube.com/@bluestar03
  #   icon: fab fa-youtube
  # - title: Ko-fi
  #   url: https://ko-fi.com/zbule
  #   icon: fa-solid fa-mug-hot