# Site Metadata
title: My Jekyll Site
lang: en

# Layout Variables (used by _includes/style.html)
panel_width: 40em
accent_color: blue
content_max: 66.67em
font_base: 16px

# Table of Contents
toc-include-h1: true

# Collections
collections:
  gdd:
    output: true
  tutorials:
    output: true

# Sidebar Navigation
nav:
  - title: "Home"
    url: /

  - title: "GDD"
    url: /gdd/

  - title: "Tutorials"
    url: /tutorials/

  - title: "Devlog"
    url: /posts/

  - title: "About"
    url: /about/

# Social Links (footer)
social:
  - title: DeviantArt
    url: https://deviantart.com/zbule
    icon: "ğŸ–¼ï¸"

  - title: Twitter
    url: https://twitter.com/yourhandle
    icon: "ğŸ¦"

  - title: GitHub
    url: https://github.com/yourhandle
    icon: "ğŸ™"
